### ISSUE TITLE
Cannot select to boot from live USB

### ISSUE THREAD

**Issue by onbjerg** [aroman/freya-on-a-mac#25]
When I choose to boot from the liveUSB in reFIND it says something about USB not being found during legacy loader.

halp

I've gotten a Mac today from work, not a big fan, wanted to install Elementary OS.

**Comment by sdaitzman** [comment]
Hey,

What point do you get to? It sounds like it shows up as "legacy boot" and you're able to choose that in rEFInd. Does it fail then or display another menu first?

**Comment by onbjerg** [comment]
I get to choose my live disk from the rEFInd menu. I then get to another screen where it displays the error message. If I press any key, I get back to the main rEFInd menu.

**Comment by sdaitzman** [comment]
Gotcha. Could I have a picture of the error it displays?

**Comment by onbjerg** [comment]
I have some work to do at the moment, but I will get back to you within the next few hours.

**Comment by migeorge** [comment]
I seem to be getting a similar error.

I've tried creating the usb via the GUI tool suggested and the manual process.

I downloaded the latest version of rEFInd (0.8.7), for which the install command noted in your README no longer works. I was able to ./install.sh and it seemed to work.

The specific error that shows is:

`No bootable device -- insert boot disk and press any key`

**Comment by theotix** [comment]
Same problem here

**Comment by dhpowrhost** [comment]
Same here..

**Comment by dhpowrhost** [comment]
Same here

**Comment by theotix** [comment]
I solved the problem: Start by pressing the alt key, select the correct drive, and there it works.

**Comment by onbjerg** [comment]
@theotix's solution worked for me. Forgot to close the issue.
