### ISSUE TITLE
GNU GRUB version 2.02 beta2-9

### ISSUE THREAD

**Issue by Waynekosimoto** [aroman/freya-on-a-mac#29]
Whenever I try to boot I get a terminal with the name of this title. But before this terminal appears in a flash text reads: 

"error: failure reading sector 0x0 from 'hd0'.
error: failure reading sector 0x0 from 'hd0'.
error no such device: ec337125-e7cf-4960...

**Comment by sdaitzman** [comment]
I've seen this issue twice with different causes each time. Did you choose "Try Elementary" and then run `$ ubiquity -b` when installing? Where did you get your ISO file from?

**Comment by Waynekosimoto** [comment]
Yes I did that. I got the ISO from elementary os' website. I actually did it twice to make sure It wasn't an issue in installation.

**Comment by Waynekosimoto** [comment]
#:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Macintosh HD            382.4 GB   disk0s2
   3:       Microsoft Basic Data                         117.4 GB   disk0s3

This is what I get when I do "$ diskutil list /dev/disk0" in case you need it.

**Comment by Waynekosimoto** [comment]
My error there was two different Os but I would hit the one with the Ubuntu logo instead of the unmarked one.

**Comment by sdaitzman** [comment]
Haha gotcha. Glad you figured that out :smile:
